#!/bin/bash

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

FONT="JetBrainsMono Nerd Font:Bold:12.0"
FONT_SMALL="JetBrainsMono Nerd Font:Bold:11.0"
FONT_TINY="JetBrainsMono Nerd Font:Bold:10.0"
ICON_FONT="JetBrainsMono Nerd Font:Bold:12.0"

export SHOW_EMPTY_WORKSPACES=false

##### Bar Appearance #####
sketchybar --bar height=34        \
                 position=top     \
                 padding_left=6   \
                 padding_right=6  \
                 display=all      \
                 notch_width=200  \
                 notch_offset=0   \
                 notch_display=main \
                 color=$BAR_COLOR


##### Defaults #####
sketchybar --default icon.font="$ICON_FONT" \
                     icon.color=$WHITE     \
                     label.font="$FONT"    \
                     label.color=$WHITE    \
                     background.color=$COLOR_PILL   \
                     background.corner_radius=9     \
                     background.height=24           \
                     background.drawing=on          \
                     padding_left=6                 \
                     padding_right=6                \
                     label.padding_left=6           \
                     label.padding_right=6          \
                     icon.padding_left=6            \
                     icon.padding_right=6

sketchybar --add event display_change

sketchybar --add item display_router right \
           --set display_router drawing=off \
                              script="$PLUGIN_DIR/display_router.sh" \
                              update_freq=5 \
           --subscribe display_router display_change system_woke

sketchybar --add item space_monitor_router left \
           --set space_monitor_router drawing=off \
                               script="$ITEM_DIR/space_monitor.sh" \
           --subscribe space_monitor_router display_change system_woke aerospace_workspace_change

# -- Left Side Items --
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/space_monitor.sh"
source "$ITEM_DIR/focus_monitor.sh"

# -- Right Side Items --
source "$ITEM_DIR/net_monitor.sh"
source "$ITEM_DIR/wifi_monitor.sh"
source "$ITEM_DIR/ble_monitor.sh"
source "$ITEM_DIR/audio_output.sh"
source "$ITEM_DIR/cpu_monitor.sh"
source "$ITEM_DIR/mem_monitor.sh"
source "$ITEM_DIR/disk_monitor.sh"
source "$ITEM_DIR/bat_monitor.sh"
source "$ITEM_DIR/clock.sh"

sketchybar --update
"$PLUGIN_DIR/display_router.sh"
